export const DOCUMENTO_REQUEST = 'DOCUMENTO_REQUEST';
export const DOCUMENTO_SUCCESS = 'DOCUMENTO_SUCCESS';
export const DOCUMENTO_FAILURE = 'DOCUMENTO_FAILURE';
export const LIMPIAR_MSG = 'LIMPIAR_MSG';
export const DOCUMENTO_LISTADO = 'DOCUMENTO_LISTADO';
