export const EVENTO_REQUEST = 'EVENTO_REQUEST';
export const NEW_EVENTO_SUCCESS = 'NEW_EVENTO_SUCCESS';
export const EVENTO_FAILURE = 'EVENTO_FAILURE';

export const LISTAR_EVENTOS_SUCCESS = 'LISTAR_EVENTOS_SUCCESS';
export const OBTENER_EVENTO_SUCCESS = 'OBTENER_EVENTO_SUCCESS';
export const ACTUALIZAR_EVENTO_SUCCESS = 'ACTUALIZAR_EVENTO_SUCCESS';
export const ELIMINAR_EVENTO_SUCCESS = 'ELIMINAR_EVENTO_SUCCESS';
