export const TRAMITE_REQUEST = 'TRAMITE_REQUEST';
export const TRAMITE_SUCCESS = 'TRAMITE_SUCCESS';
export const TRAMITE_FAILURE = 'TRAMITE_FAILURE';
export const LIMPIAR_MSG = 'LIMPIAR_MSG';

export const TRAMITES_LISTADO = 'TRAMITES_LISTADO';
