export const TIPO_DOCUMENTO_REQUEST = 'TIPO_DOCUMENTO_REQUEST';
export const TIPO_DOCUMENTO_SUCCESS = 'TIPO_DOCUMENTO_SUCCESS';
export const TIPO_DOCUMENTO_FAILURE = 'TIPO_DOCUMENTO_FAILURE';
export const LIMPIAR_MSG = 'LIMPIAR_MSG';
export const TIPO_DOCUMENTOS_LISTADO = 'TIPO_DOCUMENTOS_LISTADO';
