export const TURISMO_REQUEST = 'TURISMO_REQUEST';
export const NEW_TURISMO_SUCCESS = 'NEW_TURISMO_SUCCESS';
export const TURISMO_FAILURE = 'TURISMO_FAILURE';

export const LISTAR_TURISMOS_SUCCESS = 'LISTAR_TURISMOS_SUCCESS';
export const OBTENER_TURISMO_SUCCESS = 'OBTENER_TURISMO_SUCCESS';
export const ACTUALIZAR_TURISMO_SUCCESS = 'ACTUALIZAR_TURISMO_SUCCESS';
export const ELIMINAR_TURISMO_SUCCESS = 'ELIMINAR_TURISMO_SUCCESS';
